version: '3.8'

services:
  nginx-ingress:
    image: nginx
    ports:
      - "80:80"
      - "443:443"  # If you want to support HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  gogs:
    image: petrobubka/my_gogs_image:16
    ports:
      - "3000:3000"
      - "2222:22"
    deploy:
      replicas: 2
      labels:
        - "nginx.host=gogs.local"
      resources:
        limits:
          cpus: '0.1'
    volumes:
      - gogs-data:/mnt
    depends_on:
      - postgresdb  # Ensure that Gogs starts after PostgreSQL

  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gogsapp
      POSTGRES_USER: gogsapp
      POSTGRES_PASSWORD: gogspass
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  gogs-data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/data/app'
      o: 'bind'
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/data/db'
      o: 'bind'
